title: CS4850-KI-1-AI-Security
description: With the advancement of Artificial Intelligence (AI) technology, it is used in every part of our life, e.g., finance, security system, autonomous vehicle, cybersecurity, and transportation system. But based detectors. This might create a catastrophic effect on many security-critical systems. Government organizations, such as US Navy, US Army, and many private sectors, e.g., Uber and Google, use remote sensing data. Satellite imagery, one of the most popular remote sensing products, is widely used to monitor objects remotely. In this project, Student will explore the potential vulnerabilities of the AI models in remote sensing-based AI models and developing mitigation techniques.
remote_theme: just-the-docs/just-the-docs

url: https://KI-1-AI-Sec.github.io

logo: "assets/patch_retrained.png"

favicon_ico: "assets/favicon.ico"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
