title: CS4850-KI-1-AI-Security
description: KI-1-AI-Security Senior Project for CS4850. Adversarial-Attacks-in-ML-based
Remote-Sensing-Applications
remote_theme: just-the-docs/just-the-docs

url: https://KI-1-AI-Sec.github.io

logo: "assets/patch_retrained.png"

favicon_ico: "assets/favicon.ico"

aux_links:
  KI-1-AI-Sec Adversarial yolo: https://github.com/KI-1-AI-Sec/adversarial-yolo
