title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://KI-1-AI-Sec.github.io

logo: "assets/patch_retrained.png"

favicon_ico: "assets/favicon.ico"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
