title: CS4850-KI-1-AI-Security
description: KI-1-AI-Security Senior Project for CS4850. Adversarial-Attacks-in-ML-based Remote-Sensing-Applications
baseurl: "/KI-1-AI-Sec" 
url: "https://ki-1-ai-sec.github.io//" 
github_username: Sinister6th

nav_external_links:
  - title: KI-1-AI-Sec on GitHub
    url: https://github.com/KI-1-AI-Sec/KI-1-AI-Sec

url: https://KI-1-AI-Sec.github.io

logo: "assets/patch_retrained.png"

favicon_ico: "assets/favicon.ico"

aux_links:
  KI-1-AI-Sec Adversarial yolo: 
    - "//github.com/KI-1-AI-Sec/adversarial-yolo

    
# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-redirect-from
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
